### ISSUE TITLE
A little issue when challenge can be solved by a simple click

### ISSUE THREAD

**Issue by FlabbySheep** [thicccat688/selenium-recaptcha-solver#10]
**Describe the bug**
Hi, firstly thank you for your great project. I've found a little issue when challenge can be solved by a simple click. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to solver.py
2. find line 72 "checkbox.get_attribute('checked')"
3. When the challenge is solved without any image recognition or audio recognition, the *aria-checked* attribute of checkbox should be 'true', or it will return 'false'.

**Screenshots**
<img width="491" alt="1680650866891" src="https://user-images.githubusercontent.com/104988058/229944317-9279a927-e079-4c4a-9d46-439609267f3c.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 111
 - driver: undetected_chromedriver

**My solution**
use
`if checkbox.get_attribute('aria-checked') == 'true':
            return`

instead of 
`if checkbox.get_attribute('checked'):
            return`

**Comment by thicccat688** [comment]
Hi,

Thanks for your feedback on the project. 

I've incorporated your changes, and I'll mention you in the new release so you get credit for spotting this.

Have a nice day :)
