### ISSUE TITLE
Chrome realizes it's an automated request as soon as the solver clicks 'listen to recording'

### ISSUE THREAD

**Issue by charizardmatok** [thicccat688/selenium-recaptcha-solver#12]
So the solver clicks the 'not a robot' checkbox, the images appear, and as soon as it clicks 'listen to recording', a message is printed out and the captcha is disabled, the message says:

“Your Computer May Be Sending Automated Queries"

This renders my selenium bot useless and helpless as any following attempts to solve captchas give the same result.

**Expected behaviour**
The recording is chosen, the transcript is written for submission and the captcha is solved.

**Desktop (please complete the following information):**
 - Chrome
 - 112
 - 
**Additional context**
This is my undetected browser and solver setup:
``
ua = 'Mozilla/5.0 (Windows NT 4.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36'

options = webdriver.ChromeOptions()

options.add_argument("--window-size=1920,1080")

options.add_argument(f'--user-agent={ua}')
options.add_argument('--incognito')

options.add_argument('--no-sandbox')
options.add_argument("--disable-extensions")

browser = webdriver.Chrome(options=options)

solver = RecaptchaSolver(driver=browser, delay_config=StandardDelayConfig(min_delay=2, max_delay=3))
``

**Comment by thicccat688** [comment]
Hi,

This happens because your IP reputation is low or you've solved too many challenges in a row.

This package already has built-in bypasses for most checks but can't bypass IP blacklists, so try using/rotating proxies with your web driver to make the problem go away. Otherwise, you can wait a few hours for Google to unblacklist your IP and keep solving then.

Let me know if anything needs to be clarified, and thanks for making this issue.

**Comment by maximusrus** [comment]
I have the same issue rn and switching IPs does not help =(

**Comment by thicccat688** [comment]
Hi @maximusrus,

Thanks for letting me know.

I'm going to try out using a regular chrome driver and see how it performs; If it works, I'll deploy a new version of the package using a regular web driver instead.

**Comment by thicccat688** [comment]
Hi, 

To get back to you both, the tests I've done were mixed, but they generally seem to point out that there is something wrong with the undetected Chrome driver.

I'll update the example to use a regular Chrome driver for now. 

Thank you both!
