### ISSUE TITLE
solver does not solve captcha with audio.

### ISSUE THREAD

**Issue by 4grotten** [thicccat688/selenium-recaptcha-solver#13]
Sorry for my English. In general, the problem is that the solver solves the captcha when you only need to click the checkmark, otherwise the solver does not cope, when the captcha picture opens, it goes to audio, then to audio, it does not insert words and cannot pass it, selenium closes.

I do everything exactly as shown in the example, maybe I missed something?

**Comment by 4grotten** [comment]
```driver = undetected_chromedriver.Chrome()
solver = RecaptchaSolver(driver=driver, delay_config=StandardDelayConfig(min_delay=2, max_delay=3))
        recaptcha_iframe = driver.find_element(By.XPATH, '//iframe[@title="reCAPTCHA"]')
        solver.click_recaptcha_v2(iframe=recaptcha_iframe)```

**Comment by AimBought** [comment]
> Sorry for my English. In general, the problem is that the solver solves the captcha when you only need to click the checkmark, otherwise the solver does not cope, when the captcha picture opens, it goes to audio, then to audio, it does not insert words and cannot pass it, selenium closes.
> 
> I do everything exactly as shown in the example, maybe I missed something?

Hello :) Had same problem as you and happily solved it and should work for you too.
Firstly for me after running program it said: `(PATH ON MY PC):170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)`
So I goolged that "ffmpeg" thing and followed this video to download it: https://www.youtube.com/watch?v=IECI72XEox0&ab_channel=TroubleChute.
After following video you should have 3 files that are mentioned and many people on the internet said that you should put them in path(enviromental variables on windows) and thats generally correct(depends on what you want to do but for us it should be same issue), however it didn't work for me so what i did is i put those 3 files (ffmpeg, ffplay, ffprobe) inside where my python file is and it showed no more errors and utmost it finally solved captcha. I hope it will help you if you have some questions feel free to ask 👍

**Comment by thicccat688** [comment]
Hey,

Make sure you have FFmpeg installed, as @AimBought said. 

If you want to download it directly, there is a link in the README, or follow the tutorial that @AimBought sent.

If it's unclear that FFmpeg is required, please let me know, and I'll make a section specifically for it. 

Thank you both, and I'm sorry for the delay in my response!
