### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by AnshumanPM** [thicccat688/selenium-recaptcha-solver#23]
File "/usr/src/app/gen.py", line 15, in <module>
    from selenium_recaptcha_solver import RecaptchaSolver
ImportError: cannot import name 'RecaptchaSolver' from 'selenium_recaptcha_solver' (/usr/local/lib/python3.10/dist-packages/selenium_recaptcha_solver/__init__.py)

**Comment by thicccat688** [comment]
Hi, you need to have the package installed correctly to not get this error. Can you try to install the package using this command `python -m pip install selenium-recaptcha-solver`? 

Let me know if it still gives you trouble.
