### ISSUE TITLE
quiet / silent log level doesn't exist?

### ISSUE THREAD

**Issue by ClydexGG** [thicccat688/selenium-recaptcha-solver#24]
is there a quiet / silent log level? i couldn't find it in docs, sorry if this is not the place to ask, new to github.

**i don't want this to print:**
{   'confidence': 0.78803301,
                           'transcript': 'play without replacing the'},
                       {   'confidence': 0.82463574,
                           'transcript': 'it without replacing the'},
                       {   'confidence': 0.94446772,
                           'transcript': 'without replacing the'},
                       {   'confidence': 0.67238677,
                           'transcript': 'play without replacing the what'},
                       {   'confidence': 0.70084095,
                           'transcript': 'it without replacing the what'}],

**Comment by thicccat688** [comment]
Hi, I've looked into it, and the latest SpeechRecognition module version has a lot of print statements, which is the cause. 

The only way I've seen to stop that from being printed is to downgrade from version 3.9.0 to 3.8.1, which I've done. It should no longer print out those messages if you do `python -m pip install SpeechRecognition==3.8.1`.
