### ISSUE TITLE
Delay after solve on click and on crash

### ISSUE THREAD

**Issue by chaush-server** [thicccat688/selenium-recaptcha-solver#25]
Hi, I really like your work, but I have a wish. When the captcha is solved simply by clicking, the script waits for about 3 more seconds after which it continues to work, and also when google issues that it has detected the script, it also stops executing subsequent commands with a long delay, is it possible to manage these delays somewhere, as I understand the standard ones are not suitable for this. I will be very grateful for the answer.

**Comment by thicccat688** [comment]
Hi,

Thank you for the kind words.

If you'd like to remove the delays entirely, you can omit the StandardDelay() like this:
`solver = RecaptchaSolver(driver=test_driver)`

If you want to decrease them, you can do something like this to make the minimum delay 1 second and the maximum delay 2 seconds:
`solver = RecaptchaSolver(driver=test_driver, delay_config=StandardDelayConfig(min_delay=1, max_delay=2))`

When it comes to Google ReCAPTCHA blocking automated solving, you have three things that help you get around it (The last two methods are the best fixes):

- Wait before trying again.
- Rotate your IP by using a proxy with your web driver.
- Rotate your user-agent regularly.

I hope this answers your question for you. Let me know if you have any other questions!
