### ISSUE TITLE
from selenium_recaptcha_solver import API error

### ISSUE THREAD

**Issue by python31415926** [thicccat688/selenium-recaptcha-solver#6]
Exception has occurred: ImportError
cannot import name 'API' from 'selenium_recaptcha_solver' (C:\Users\Denis\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium_recaptcha_solver\__init__.py)
  File "C:\python\code\bookT.py", line 1, in <module>
    from selenium_recaptcha_solver import API
ImportError: cannot import name 'API' from 'selenium_recaptcha_solver' (C:\Users\Denis\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium_recaptcha_solver\__init__.py)

**Comment by thicccat688** [comment]
Hey,

Can you send me the version of the package you are using (You can check using  `python3 -m pip show selenium-recaptcha-solver`)?

Thanks

**Comment by thicccat688** [comment]
Hi @python31415926,

I will close this issue, but if you need anything, please re-open it!
