### ISSUE TITLE
Support Threading

### ISSUE THREAD

**Issue by Gandlfer** [thicccat688/selenium-recaptcha-solver#8]
**Is your feature request related to a problem? Please describe.**
Wanting to do multiple instance of recaptcha at the same time.

**Describe the solution you'd like**
Supports threading

**Describe alternatives you've considered**
Did consider to do a queue to do one by one but its too slow if there are too many threads

Additional:
I see the audio file is stored as a tempfile in the temp directory and later going through ffmpeg. Threading would cause a clash between them because they are all reading and writing from an existing file.

**Comment by thicccat688** [comment]
Hi again @Gandlfer,

I've made the changes I mentioned, so feel free to upgrade the package using pip and try it out. 

Let me know if you encounter any issues :)

**Comment by Gandlfer** [comment]
Tested the updated package. Seems to work well.
Thank you and great job!
I will open another issue if there are any bugs i encountered.
